name: Build and Release Veebee

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        shell: bash

      - name: Install dependencies
        run: bun install

      - name: Build Veebee executable
        run: bun build index.ts --compile --outfile "veebee-${VERSION}.exe"

      - name: Create release directory
        run: mkdir release

      - name: Copy extra files
        run: |
          cp "veebee-${VERSION}.exe" release/
          cp CONTRIBUTING.md release/ || true
          cp CODE_OF_CONDUCT.md release/ || true
          cp README.md release/ || true
          cp LICENSE release/ || true
          cp LICENSE_GPLv3 release/ || true
          cp .env.example release/ || true

      - name: Zip release
        run: zip -r "veebee-${VERSION}.zip" release

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Veebee ${{ github.ref_name }}
          artifacts: "veebee-${VERSION}.zip"
          draft: false
          prerelease: false
