name: Build and Release

on:
  push:
    tags:
      - '*'

env:
  VERSION: ${{ github.ref_name }}

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Bun
        run: |
          iwr -useb https://bun.sh/install | iex
          Add-Content -Path $env:GITHUB_PATH -Value "$env:USERPROFILE\.bun\bin"

      - name: Install dependencies
        run: bun install

      - name: Build EXE
        run: bun build index.ts --compile --outfile "veebee-${env:VERSION}.exe"

      - name: Create ZIP
        id: zip
        run: |
          $zipName = "veebee-${env:VERSION}.zip"
          Compress-Archive -Path "veebee-${env:VERSION}.exe","CONTRIBUTING.md","CODE_OF_CONDUCT.md","README.md","LICENSE","LICENSE_GPLv3",".env.example" -DestinationPath $zipName
          echo "zip_name=$zipName" >> $env:GITHUB_ENV
          echo "::set-output name=zip::$zipName"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.zip.outputs.zip }}
          asset_path: ${{ steps.zip.outputs.zip }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
